{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":219484398,"authorName":"sriram_varahan1","from":"&quot;sriram_varahan1&quot; &lt;sriram_varahan1@...&gt;","profile":"sriram_varahan1","replyTo":"LIST","senderId":"M372_kboI4FvIR-Mq2MqGueHB7z9j7Cb6HpesAX-rhGrJYPabtUfxSYV2TUBH5xDa49F9s0uXk0uXabl77V2Z5e9psdIXNSotUVT9z095t-6_zV1","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Unhandled exception while running Heritrix","postDate":"1274253413","msgId":6526,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGh0MDM5NSs0amptQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":6533,"prevInTime":6525,"nextInTime":6527,"topicId":6526,"numMessagesInTopic":6,"msgSnippet":"Hello, I have been running Heritrix for some time and recently I got this strange exception while launching a job. The details from the job.log are as follows:","rawEmail":"Return-Path: &lt;sriram_varahan1@...&gt;\r\nX-Sender: sriram_varahan1@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 79605 invoked from network); 19 May 2010 07:18:17 -0000\r\nX-Received: from unknown (98.137.34.46)\n  by m13.grp.re1.yahoo.com with QMQP; 19 May 2010 07:18:17 -0000\r\nX-Received: from unknown (HELO n37b.bullet.mail.sp1.yahoo.com) (66.163.168.151)\n  by mta3.grp.sp2.yahoo.com with SMTP; 19 May 2010 07:18:16 -0000\r\nX-Received: from [69.147.65.149] by n37.bullet.mail.sp1.yahoo.com with NNFMP; 19 May 2010 07:16:53 -0000\r\nX-Received: from [98.137.34.35] by t9.bullet.mail.sp1.yahoo.com with NNFMP; 19 May 2010 07:16:53 -0000\r\nDate: Wed, 19 May 2010 07:16:53 -0000\r\nTo: archive-crawler@yahoogroups.com\r\nMessage-ID: &lt;ht0395+4jjm@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0:0\r\nFrom: &quot;sriram_varahan1&quot; &lt;sriram_varahan1@...&gt;\r\nSubject: Unhandled exception while running Heritrix\r\nX-Yahoo-Group-Post: member; u=219484398; y=K1ARe88bGNda5ijMkjTvl1w2bOnT-n9pc5sqZP-i5wRVTj_9EGKSDi8l\r\nX-Yahoo-Profile: sriram_varahan1\r\n\r\nHello,\n\n     I have been running Heritrix for some time and recently I got =\r\nthis strange exception while launching a job. The details from the job.log =\r\nare as follows:\n\n\n2010-05-18T15:43:47.929Z SEVERE Unhandled exception or er=\r\nror intercepted\n2010-05-18T15:43:47.993Z INFO Job instance discarded\n2010-0=\r\n5-18T15:43:48.364Z INFO Job instantiated\n2010-05-18T15:43:48.452Z INFO Job =\r\nlaunched\n2010-05-18T15:43:48.576Z SEVERE RuntimeException: com.sleepycat.je=\r\n.EnvironmentFailureException: (JE 4.0.71) Environment must be closed, cause=\r\nd by: com.sleepycat.je.EnvironmentFailureException: Environment invalid bec=\r\nause of previous exception: (JE 4.0.71) /root/test_job/state com.sleepycat.=\r\nje.log.ChecksumException: Read invalid log entry type: 99 LOG_CHECKSUM: Che=\r\ncksum invalid on read, log is likely invalid. Environment is invalid and mu=\r\nst be closed. fetchTarget of 0x0/0x40904a parent IN=3D13 IN class=3Dcom.sle=\r\nepycat.je.tree.BIN lastFullVersion=3D0x2/0xb1fb2 parent.getDirty()=3Dfalse =\r\nstate=3D0 (in thread &#39;test_job launchthread&#39;)\n2010-05-18T15:43:50.051Z SEVE=\r\nRE Unhandled exception or error intercepted\n\n\nCan someone please shed some =\r\nlight on the error and what I would need to do to avoid this in the future.=\r\n\n\nThanks,\nSriram.\n\n\n"}}